# Generated by Django 2.1.7 on 2019-03-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_link_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
