sudo: required
services:
  - docker

before_install:
  - docker build -t davidvartanian/ls-shortener-$TRAVIS_BRANCH ./linkshortener
  - docker build -t davidvartanian/ls-auth-$TRAVIS_BRANCH ./auth

script:
  - docker run davidvartanian/ls-shortener python manage.py test
  - docker run davidvartanian/ls-auth python manage.py test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push davidvartanian/ls-shortener-$TRAVIS_BRANCH
  - docker push davidvartanian/ls-auth-$TRAVIS_BRANCH