version: '3'

services:
  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    ports:
      - "${AUTH_PORT}:80"
    restart: on-failure
    volumes:
      - "./auth:/app"
    environment:
      - "DEBUG=True"
  linkshortener:
    build:
      context: linkshortener
      dockerfile: Dockerfile
      #    command: python apiplatform/manage.py runserver 0.0.0.0:8000
    ports:
      - "${API_PORT}:80"
    environment:
      - "AUTH_URL=http://auth"
      - "DEBUG=True"
    restart: on-failure
    volumes:
      - "./linkshortener:/app"